name: Easy-mode Integration (legacy)

on:
  workflow_dispatch: {}

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legacy workflow retained for history; easy-mode is deprecated. Use proxy-first docs."
