name: Release (legacy, dispatch-only)
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
      - name: Build Matrix
        run: |
          mkdir -p dist
          platforms="linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64"
          for p in $platforms; do
            GOOS=${p%/*}; GOARCH=${p#*/};
            out="sb29guard-${GOOS}-${GOARCH}"
            if [ "$GOOS" = "windows" ]; then out="$out.exe"; fi
            echo "Building $out";
            GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "-s -w" -o dist/$out ./cmd/sb29guard || exit 1;
          done
          (cd dist && sha256sum * > SHA256SUMS)
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
